#ServerProperites
server:
  port: 8080
  servlet:
    context-path: /community


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=Asia/Shanghai #UTC会差8个小时
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource #springboot内置的性能最好的连接池
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000  #连接空闲30000ms才关掉

  thymeleaf:
    cache: false #ThymeleafProperites

  mail:
    host: smtp.sina.com
    port: 465
    username: memgyuchao@sina.com
    password: 132c7e27c93073b3
    protocol: smtps
    properties.mail.smtp.ssl.enable: true

  redis:
    port: 6379
    host: localhost
    database: 11

  #KafkaProperties
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000

  data:
    elasticsearch:
      #      cluster-name: nowcoder
      #      cluster-nodes:
      repositories:
        enabled: true

  elasticsearch:
    rest:
      uris: http://localhost:9201


mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-generated-keys: true #启用自动生成主键
    map-underscore-to-camel-case: true  #驼峰命名转换 字段与实体的匹配
  type-aliases-package: com.yuchao.community.entity  #resultType可以使用类名


#logging:
#  level:
#    com.yuchao: debug
#  file:
#    path: spring.log


community.path:
  domain: http://localhost:8080
  upload: E:\Users\Desktop\community\image